version: "2.4"
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1M"
    max-file: "10"
services:
  jsxc:
    image: jsxc/jsxc-single-page:latest
    build: ./
    env_file: .env.docker.local
    ports:
      - 3000:3000
    networks:
      - proxy
    restart: always
    logging: *default-logging
networks:
  proxy:
